/// <mls fileReference="_102034_/l1/monitor/persistence.ts" enhancement="_blank" />
import type { TableDefinition } from '/_102034_/l1/server/layer_1_external/persistence/contracts.js';

export const tableDefinitions: TableDefinition[] = [
  {
    moduleId: 'monitor',
    repositoryName: 'monitorBffExecutionLog',
    tableName: 'monitor_bff_execution_log',
    purpose: 'controle',
    description: 'BFF execution log for monitor dashboards.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'requestId', postgresType: 'TEXT' },
      { name: 'traceId', postgresType: 'TEXT' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'pageName', postgresType: 'TEXT' },
      { name: 'command', postgresType: 'TEXT' },
      { name: 'source', postgresType: 'TEXT' },
      { name: 'statusCode', postgresType: 'INTEGER' },
      { name: 'statusGroup', postgresType: 'TEXT' },
      { name: 'ok', postgresType: 'BOOLEAN' },
      { name: 'durationMs', postgresType: 'INTEGER' },
      { name: 'errorCode', postgresType: 'TEXT', nullable: true },
      { name: 'startedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'finishedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_monitor_bff_log_routine', columns: ['routine'] },
      { name: 'idx_monitor_bff_log_module', columns: ['module'] },
      { name: 'idx_monitor_bff_log_page', columns: ['pageName'] },
      { name: 'idx_monitor_bff_log_status_code', columns: ['statusCode'] },
      { name: 'idx_monitor_bff_log_status_group', columns: ['statusGroup'] },
      { name: 'idx_monitor_bff_log_finished_at', columns: ['finishedAt'] },
    ],
    version: 1,
  },
  {
    moduleId: 'monitor',
    repositoryName: 'monitorBffExecutionAggMinute',
    tableName: 'monitor_bff_execution_agg_minute',
    purpose: 'controle',
    description: 'Minute-level BFF execution aggregation for monitor dashboards.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'bucketStart', postgresType: 'TIMESTAMPTZ' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'pageName', postgresType: 'TEXT' },
      { name: 'command', postgresType: 'TEXT' },
      { name: 'source', postgresType: 'TEXT' },
      { name: 'statusCode', postgresType: 'INTEGER' },
      { name: 'statusGroup', postgresType: 'TEXT' },
      { name: 'totalCount', postgresType: 'INTEGER' },
      { name: 'successCount', postgresType: 'INTEGER' },
      { name: 'clientErrorCount', postgresType: 'INTEGER' },
      { name: 'serverErrorCount', postgresType: 'INTEGER' },
      { name: 'notFoundCount', postgresType: 'INTEGER' },
      { name: 'totalDurationMs', postgresType: 'INTEGER' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_monitor_bff_agg_bucket', columns: ['bucketStart'] },
      { name: 'idx_monitor_bff_agg_routine', columns: ['routine'] },
      { name: 'idx_monitor_bff_agg_status_group', columns: ['statusGroup'] },
    ],
    version: 1,
  },
];
