/// <mls fileReference="_102034_/l1/mdm/persistence.ts" enhancement="_blank" />
import type { TableDefinition } from '/_102034_/l1/server/layer_1_external/persistence/contracts.js';

export const tableDefinitions: TableDefinition[] = [
  {
    moduleId: 'mdm',
    repositoryName: 'mdmEntityIndex',
    tableName: 'mdm_documents_entities_index',
    tableNameByEnv: {
      staging: 'mdm_documents_entities_index_test',
    },
    purpose: 'mdm',
    description: 'Permanent MDM entity index table for queries and joins.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'mdmId', postgresType: 'TEXT' },
      { name: 'subtype', postgresType: 'TEXT' },
      { name: 'name', postgresType: 'TEXT' },
      { name: 'status', postgresType: 'TEXT' },
      { name: 'docType', postgresType: 'TEXT', nullable: true },
      { name: 'docId', postgresType: 'TEXT', nullable: true },
      { name: 'countryCode', postgresType: 'TEXT' },
      { name: 'tags', postgresType: 'TEXT[]', defaultSql: '\'{}\'::text[]' },
      { name: 'searchVector', postgresType: 'TEXT' },
      { name: 'mergedInto', postgresType: 'TEXT', nullable: true },
      { name: 'dynamoPk', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['mdmId'],
    indexes: [
      { name: 'idx_mdm_entity_subtype', columns: ['subtype'] },
      { name: 'idx_mdm_entity_name', columns: ['name'] },
      { name: 'idx_mdm_entity_status', columns: ['status'] },
      { name: 'idx_mdm_entity_doctype', columns: ['docType'] },
      { name: 'idx_mdm_entity_docid', columns: ['docId'] },
      { name: 'idx_mdm_entity_country', columns: ['countryCode'] },
      { name: 'idx_mdm_entity_dynamopk', columns: ['dynamoPk'] },
      { name: 'idx_mdm_entity_createdat', columns: ['createdAt'] },
      { name: 'idx_mdm_entity_updatedat', columns: ['updatedAt'] },
    ],
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmProspectIndex',
    tableName: 'mdm_documents_prospects_index',
    tableNameByEnv: {
      staging: 'mdm_documents_prospects_index_test',
    },
    purpose: 'mdm',
    description: 'Transient MDM prospect index table.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'mdmId', postgresType: 'TEXT' },
      { name: 'subtype', postgresType: 'TEXT' },
      { name: 'name', postgresType: 'TEXT' },
      { name: 'status', postgresType: 'TEXT' },
      { name: 'docType', postgresType: 'TEXT', nullable: true },
      { name: 'docId', postgresType: 'TEXT', nullable: true },
      { name: 'countryCode', postgresType: 'TEXT' },
      { name: 'tags', postgresType: 'TEXT[]', defaultSql: '\'{}\'::text[]' },
      { name: 'promotionSource', postgresType: 'TEXT' },
      { name: 'promotedTo', postgresType: 'TEXT', nullable: true },
      { name: 'ttlExpiresAt', postgresType: 'TIMESTAMPTZ', nullable: true },
      { name: 'dynamoPk', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['mdmId'],
    indexes: [
      { name: 'idx_mdm_prospect_subtype', columns: ['subtype'] },
      { name: 'idx_mdm_prospect_status', columns: ['status'] },
      { name: 'idx_mdm_prospect_docid', columns: ['docId'] },
      { name: 'idx_mdm_prospect_country', columns: ['countryCode'] },
    ],
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmRelationship',
    tableName: 'mdm_relationship',
    tableNameByEnv: {
      staging: 'mdm_relationship_test',
    },
    purpose: 'mdm',
    description: 'Relationship graph for permanent MDM entities with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'fromId', postgresType: 'TEXT' },
      { name: 'toId', postgresType: 'TEXT' },
      { name: 'type', postgresType: 'TEXT' },
      { name: 'role', postgresType: 'TEXT', nullable: true },
      { name: 'metadata', postgresType: 'JSONB', defaultSql: '\'{}\'::jsonb' },
      { name: 'isBidirectional', postgresType: 'BOOLEAN' },
      { name: 'validFrom', postgresType: 'DATE' },
      { name: 'validTo', postgresType: 'DATE', nullable: true },
      { name: 'status', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_relationship_fromid', columns: ['fromId'] },
      { name: 'idx_mdm_relationship_toid', columns: ['toId'] },
      { name: 'idx_mdm_relationship_type', columns: ['type'] },
      { name: 'idx_mdm_relationship_status', columns: ['status'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_relationship',
        staging: 'mdm_relationship_test',
        production: 'mdm_relationship',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmProspectRelationship',
    tableName: 'mdm_prospect_relationship',
    tableNameByEnv: {
      staging: 'mdm_prospect_relationship_test',
    },
    purpose: 'mdm',
    description: 'Relationship graph for prospect MDM entities with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'fromId', postgresType: 'TEXT' },
      { name: 'toId', postgresType: 'TEXT' },
      { name: 'type', postgresType: 'TEXT' },
      { name: 'role', postgresType: 'TEXT', nullable: true },
      { name: 'metadata', postgresType: 'JSONB', defaultSql: '\'{}\'::jsonb' },
      { name: 'isBidirectional', postgresType: 'BOOLEAN' },
      { name: 'validFrom', postgresType: 'DATE' },
      { name: 'validTo', postgresType: 'DATE', nullable: true },
      { name: 'status', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_prospect_relationship_fromid', columns: ['fromId'] },
      { name: 'idx_mdm_prospect_relationship_toid', columns: ['toId'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_prospect_relationship',
        staging: 'mdm_prospect_relationship_test',
        production: 'mdm_prospect_relationship',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmKv',
    tableName: 'mdm_kv',
    tableNameByEnv: {
      staging: 'mdm_kv_test',
    },
    purpose: 'controle',
    description: 'Shared key-value table for lightweight cross-module JSON configuration.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'key', postgresType: 'TEXT' },
      { name: 'value', postgresType: 'JSONB' },
    ],
    primaryKey: ['key'],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_kv',
        staging: 'mdm_kv_test',
        production: 'mdm_kv',
      },
      partitionKey: 'key',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmDocumentCache',
    tableName: 'mdm_documents',
    tableNameByEnv: {
      staging: 'mdm_documents_test',
    },
    purpose: 'cache',
    description: 'Local MDM document store replicated to DynamoDB.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'mdmId', postgresType: 'TEXT' },
      { name: 'version', postgresType: 'INTEGER' },
      { name: 'details', postgresType: 'JSONB' },
    ],
    primaryKey: ['mdmId'],
    postgres: {
      unlogged: true,
    },
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_documents',
        staging: 'mdm_documents_test',
        production: 'mdm_documents',
      },
      partitionKey: 'mdmId',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmOutbox',
    tableName: 'mdm_outbox',
    tableNameByEnv: {
      staging: 'mdm_outbox_test',
    },
    purpose: 'fila',
    description: 'Outbox queue for write-behind replication jobs.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'aggregateType', postgresType: 'TEXT' },
      { name: 'aggregateId', postgresType: 'TEXT' },
      { name: 'eventType', postgresType: 'TEXT' },
      { name: 'payload', postgresType: 'JSONB' },
      { name: 'attemptCount', postgresType: 'INTEGER', defaultSql: '0' },
      { name: 'processedAt', postgresType: 'TIMESTAMPTZ', nullable: true },
      { name: 'lastError', postgresType: 'TEXT', nullable: true },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'updatedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'topic', postgresType: 'TEXT' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_outbox_topic', columns: ['topic'] },
      { name: 'idx_mdm_outbox_processed', columns: ['processedAt'] },
    ],
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmReplicationFailures',
    tableName: 'mdm_replication_failures',
    tableNameByEnv: {
      staging: 'mdm_replication_failures_test',
    },
    purpose: 'fila',
    description: 'Dead-letter records for replication failures.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'outboxId', postgresType: 'TEXT' },
      { name: 'payload', postgresType: 'JSONB' },
      { name: 'errorMessage', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmAuditLog',
    tableName: 'mdm_audit_log',
    tableNameByEnv: {
      staging: 'mdm_audit_log_test',
    },
    purpose: 'controle',
    description: 'MDM audit log with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT' },
      { name: 'action', postgresType: 'TEXT' },
      { name: 'actorId', postgresType: 'TEXT' },
      { name: 'actorType', postgresType: 'TEXT' },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_audit_entity', columns: ['entityType', 'entityId'] },
      { name: 'idx_mdm_audit_actor', columns: ['actorId'] },
      { name: 'idx_mdm_audit_module_created', columns: ['module', 'createdAt'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_audit_log',
        staging: 'mdm_audit_log_test',
        production: 'mdm_audit_log',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmMonitoringWrite',
    tableName: 'mdm_monitoring_write',
    tableNameByEnv: {
      staging: 'mdm_monitoring_write_test',
    },
    purpose: 'controle',
    description: 'Operational write monitoring table for the MDM module.',
    backupHot: false,
    storageProfile: 'postgres',
    writeMode: 'sync',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT', nullable: true },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'action', postgresType: 'TEXT' },
      { name: 'success', postgresType: 'BOOLEAN' },
      { name: 'durationMs', postgresType: 'INTEGER' },
      { name: 'startedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'finishedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'actorType', postgresType: 'TEXT' },
      { name: 'source', postgresType: 'TEXT' },
      { name: 'errorCode', postgresType: 'TEXT', nullable: true },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_monitoring_module_finished', columns: ['module', 'finishedAt'] },
      { name: 'idx_mdm_monitoring_entity', columns: ['entityType', 'entityId'] },
      { name: 'idx_mdm_monitoring_success', columns: ['success', 'finishedAt'] },
    ],
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmErrorLog',
    tableName: 'mdm_error_log',
    tableNameByEnv: {
      staging: 'mdm_error_log_test',
    },
    purpose: 'controle',
    description: 'Operational error log for the MDM module.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT', nullable: true },
      { name: 'entityId', postgresType: 'TEXT', nullable: true },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'action', postgresType: 'TEXT' },
      { name: 'errorCode', postgresType: 'TEXT' },
      { name: 'message', postgresType: 'TEXT' },
      { name: 'details', postgresType: 'JSONB', nullable: true },
      { name: 'stack', postgresType: 'TEXT', nullable: true },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_error_module_created', columns: ['module', 'createdAt'] },
      { name: 'idx_mdm_error_entity', columns: ['entityType', 'entityId'] },
      { name: 'idx_mdm_error_code', columns: ['errorCode', 'createdAt'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_error_log',
        staging: 'mdm_error_log_test',
        production: 'mdm_error_log',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmStatusHistory',
    tableName: 'mdm_status_history',
    tableNameByEnv: {
      staging: 'mdm_status_history_test',
    },
    purpose: 'controle',
    description: 'MDM status history table.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT' },
      { name: 'fromStatus', postgresType: 'TEXT', nullable: true },
      { name: 'toStatus', postgresType: 'TEXT' },
      { name: 'reason', postgresType: 'TEXT', nullable: true },
      { name: 'reasonCode', postgresType: 'TEXT', nullable: true },
      { name: 'actorId', postgresType: 'TEXT' },
      { name: 'actorType', postgresType: 'TEXT' },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'routine', postgresType: 'TEXT' },
      { name: 'metadata', postgresType: 'JSONB', nullable: true },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_status_entity', columns: ['entityType', 'entityId', 'createdAt'] },
      { name: 'idx_mdm_status_transition', columns: ['module', 'fromStatus', 'toStatus'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_status_history',
        staging: 'mdm_status_history_test',
        production: 'mdm_status_history',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmTag',
    tableName: 'mdm_tag',
    tableNameByEnv: {
      staging: 'mdm_tag_test',
    },
    purpose: 'controle',
    description: 'MDM tag table with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT' },
      { name: 'tag', postgresType: 'TEXT' },
      { name: 'namespace', postgresType: 'TEXT', nullable: true },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'createdBy', postgresType: 'TEXT' },
      { name: 'createdByType', postgresType: 'TEXT' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_tag_entity', columns: ['entityType', 'entityId'] },
      { name: 'idx_mdm_tag_lookup', columns: ['entityType', 'tag', 'module'] },
      { name: 'idx_mdm_tag_namespace', columns: ['entityType', 'namespace', 'module'] },
      { name: 'idx_mdm_tag_module_tag', columns: ['module', 'tag'] },
      { name: 'idx_mdm_tag_unique', columns: ['entityType', 'entityId', 'tag', 'module'], unique: true },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_tag',
        staging: 'mdm_tag_test',
        production: 'mdm_tag',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmComment',
    tableName: 'mdm_comment',
    tableNameByEnv: {
      staging: 'mdm_comment_test',
    },
    purpose: 'controle',
    description: 'MDM comment table with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT' },
      { name: 'parentCommentId', postgresType: 'TEXT', nullable: true },
      { name: 'text', postgresType: 'TEXT' },
      { name: 'authorId', postgresType: 'TEXT' },
      { name: 'authorType', postgresType: 'TEXT' },
      { name: 'module', postgresType: 'TEXT' },
      { name: 'isSystemGenerated', postgresType: 'BOOLEAN' },
      { name: 'editedAt', postgresType: 'TIMESTAMPTZ', nullable: true },
      { name: 'deletedAt', postgresType: 'TIMESTAMPTZ', nullable: true },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_comment_entity_created', columns: ['entityType', 'entityId', 'createdAt'] },
      { name: 'idx_mdm_comment_parent', columns: ['parentCommentId'] },
      { name: 'idx_mdm_comment_author_created', columns: ['authorId', 'createdAt'] },
      { name: 'idx_mdm_comment_module_created', columns: ['module', 'createdAt'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_comment',
        staging: 'mdm_comment_test',
        production: 'mdm_comment',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmAttachment',
    tableName: 'mdm_attachment',
    tableNameByEnv: {
      staging: 'mdm_attachment_test',
    },
    purpose: 'controle',
    description: 'MDM attachment table with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'entityType', postgresType: 'TEXT' },
      { name: 'entityId', postgresType: 'TEXT' },
      { name: 'fileName', postgresType: 'TEXT' },
      { name: 'mimeType', postgresType: 'TEXT' },
      { name: 'sizeBytes', postgresType: 'INTEGER' },
      { name: 'storageKey', postgresType: 'TEXT' },
      { name: 'storageProvider', postgresType: 'TEXT' },
      { name: 'category', postgresType: 'TEXT', nullable: true },
      { name: 'uploadedBy', postgresType: 'TEXT' },
      { name: 'uploadedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'deletedAt', postgresType: 'TIMESTAMPTZ', nullable: true },
      { name: 'details', postgresType: 'JSONB', nullable: true },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_attachment_entity', columns: ['entityType', 'entityId'] },
      { name: 'idx_mdm_attachment_entity_category', columns: ['entityType', 'entityId', 'category'] },
      { name: 'idx_mdm_attachment_uploaded', columns: ['uploadedBy', 'uploadedAt'] },
      { name: 'idx_mdm_attachment_deleted', columns: ['deletedAt'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_attachment',
        staging: 'mdm_attachment_test',
        production: 'mdm_attachment',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'mdm',
    repositoryName: 'mdmNumberSequence',
    tableName: 'mdm_number_sequence',
    tableNameByEnv: {
      staging: 'mdm_number_sequence_test',
    },
    purpose: 'controle',
    description: 'MDM number sequence table with hot backup.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'sequenceKey', postgresType: 'TEXT' },
      { name: 'prefix', postgresType: 'TEXT', nullable: true },
      { name: 'currentValue', postgresType: 'INTEGER' },
      { name: 'increment', postgresType: 'INTEGER' },
      { name: 'padding', postgresType: 'INTEGER', nullable: true },
      { name: 'yearSegment', postgresType: 'BOOLEAN' },
      { name: 'scopeType', postgresType: 'TEXT' },
      { name: 'scopeId', postgresType: 'TEXT', nullable: true },
      { name: 'lastIssuedAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'createdAt', postgresType: 'TIMESTAMPTZ' },
      { name: 'details', postgresType: 'JSONB', nullable: true },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_mdm_number_sequence_key', columns: ['sequenceKey'], unique: true },
      { name: 'idx_mdm_number_sequence_scope', columns: ['scopeType', 'scopeId'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'mdm_number_sequence',
        staging: 'mdm_number_sequence_test',
        production: 'mdm_number_sequence',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
];
